# Generated by Django 5.0.2 on 2024-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_room_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='bio_options',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=100),
        ),
        migrations.AddField(
            model_name='charactercard',
            name='health_options',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=100),
        ),
        migrations.AddField(
            model_name='charactercard',
            name='phobia_options',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=100),
        ),
    ]
