# Generated by Django 5.0.2 on 2024-03-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_charactercard_bio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercard',
            name='bio_options',
        ),
        migrations.RemoveField(
            model_name='charactercard',
            name='health_options',
        ),
        migrations.RemoveField(
            model_name='charactercard',
            name='phobia_options',
        ),
    ]
