# Generated by Django 5.0.2 on 2024-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_room_current_turn_player_alter_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='player_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
