# Generated by Django 5.0.2 on 2024-03-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_place_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='player_number',
        ),
    ]
