# Generated by Django 5.0.2 on 2024-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_place_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='turn_finished',
            field=models.BooleanField(default=False),
        ),
    ]
