# Generated by Django 5.0.2 on 2024-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_place_turn_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='can_end_turn',
            field=models.BooleanField(default=False),
        ),
    ]
