# Generated by Django 5.0.2 on 2024-03-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_place_can_end_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='can_end_turn',
        ),
    ]
