# Generated by Django 5.0.2 on 2024-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_place_can_end_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='can_end_turn',
            field=models.BooleanField(default=False),
        ),
    ]
