# Generated by Django 5.0.2 on 2024-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_place_can_end_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn_ended',
            field=models.BooleanField(default=False),
        ),
    ]
