# Generated by Django 5.0.4 on 2024-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
