# Generated by Django 5.0.4 on 2024-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_place_is_kicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='initial_players_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
