# Generated by Django 5.0.4 on 2024-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_room_initial_players_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='characteristic_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='char_by_turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='game_finished',
            field=models.BooleanField(default=False),
        ),
    ]
