BIO_OPTIONS = [
    "Woman, 28 years old, able to give birth.",
    "Man, 35 years old, unable to give birth.",
    "Woman, 32 years old, able to give birth.",
    "Man, 40 years old, unable to give birth.",
    "Woman, 25 years old, able to give birth.",
    "Man, 45 years old, unable to give birth.",
    "Woman, 22 years old, able to give birth.",
    "Man, 38 years old, unable to give birth.",
    "Woman, 30 years old, able to give birth.",
    "Man, 42 years old, unable to give birth.",
    "Woman, 33 years old, able to give birth.",
    "Man, 39 years old, unable to give birth.",
    "Woman, 29 years old, able to give birth.",
    "Man, 36 years old, unable to give birth.",
    "Woman, 31 years old, able to give birth.",
    "Man, 43 years old, unable to give birth.",
    "Woman, 26 years old, able to give birth.",
    "Man, 37 years old, unable to give birth.",
    "Woman, 34 years old, able to give birth.",
    "Man, 41 years old, unable to give birth."
]

HEALTH_OPTIONS = [
    "Common Cold",
    "Headache",
    "Nausea",
    "Diarrhea",
    "Minor Injury",
    "Sprain",
    "Fracture",

    "Pneumonia",
    "Infection",
    "Radiation Sickness",
    "Poisoning",
    "Mental Disorder",
    "Severe Injury",

    "Asthma",
    "Diabetes",
    "Heart Disease",
    "Cancer",
    "Chronic Mental Disorder",
    "Disability",

    "Sepsis",
    "Internal Bleeding",
    "Stroke",
    "Heart Attack",
    "Metastatic Cancer",
]


PHOBIA_OPTIONS = [
    "Fear of heights",
    "Fear of spiders",
    "Fear of the dark",
    "Fear of public speaking",
    "Fear of enclosed spaces",
    "Fear of flying",
    "Fear of snakes",
    "Fear of crowds",
    "Fear of needles",
    "Fear of germs or dirt",
    "Fear of clowns",
    "Fear of vomiting",
    "Fear of dogs",
    "Fear of thunder and lightning",
    "Fear of being alone",
    "Fear of blood",
    "Fear of drowning",
    "Fear of fire",
    "Fear of mirrors",
    "Fear of ghosts",
]

HOBBY_OPTIONS = [
    "Painting",
    "Basketball",
    "Gaming",
    "Cooking",
    "Reading",
    "Photography",
    "Hiking",
    "Singing",
    "Dancing",
    "Writing",
    "Playing a musical instrument",
    "Fishing",
    "Gardening",
    "Cycling",
    "Knitting",
    "Woodworking",
    "Yoga",
    "Traveling",
    "Collecting stamps",
    "Chess",
    "Pottery",
]


KNOWLEDGE_OPTIONS = [
    "Know how to purify water",
    "Know basic first aid",
    "Know how to start a fire without matches",
    "Know how to identify edible plants",
    "Know how to build a shelter",
    "Know how to navigate without a compass",
    "Know basic self-defense techniques",
    "Know how to forage for food",
    "Know how to preserve food",
    "Know how to tie various knots",
    "Know how to make basic tools",
    "Know how to identify signs of dangerous weather",
    "Know how to signal for help",
    "Know how to administer CPR",
    "Know how to set traps for small game",
    "Know how to mend clothing",
    "Know how to construct simple weapons for self-defense",
    "Know how to identify different types of terrain",
    "Know how to find or create sources of light",
    "Know how to navigate using the stars",
]


ADDITIONAL_INFO_OPTIONS = [
    "Know how to perform basic car maintenance",
    "Speak multiple languages fluently",
    "Have experience in wilderness survival",
    "Know how to operate various types of firearms",
    "Have a background in engineering or mechanics",
    "Have medical training or experience",
    "Be proficient in coding or computer programming",
    "Have experience in farming or agriculture",
    "Know how to navigate using celestial navigation",
    "Have experience in hunting or tracking",
    "Be skilled in negotiation and diplomacy",
    "Possess knowledge of local flora and fauna",
    "Have experience in construction or carpentry",
    "Know how to generate electricity from alternative sources",
    "Be trained in martial arts or self-defense",
    "Possess knowledge of herbal medicine",
    "Have experience in off-grid living",
    "Be proficient in wilderness cooking",
    "Possess knowledge of radio communication",
    "Be skilled in improvisation and problem-solving",
]


LUGGAGE_OPTIONS = [
    "3 AK-47",
    "The block of water",
    "Seeds",
    "First aid kit",
    "Multi-tool",
    "Solar-powered charger",
    "Portable water filter",
    "Tent",
    "Sleeping bag",
    "Canned food",
    "Fire starter kit",
    "Flashlight with extra batteries",
    "Map and compass",
    "Emergency shelter",
    "Survival knife",
    "Portable stove",
    "Rope or paracord",
    "Emergency blanket",
    "Signal mirror",
    "Whistle",
    "Duct tape",
    "Emergency radio",
    "Fishing gear",
    "Compact axe or hatchet",
    "Emergency cash",
    "Personal hygiene items",
    "Notepad and pen",
    "Solar blanket",
]
